language: node_js
node_js:
  - lts/*
dist: trusty
env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest
  sonarcloud:
    organization: alexandersarson
    token:
      secure: $SONAR_TOKEN
  apt:
    packages:
      - libgconf-2-4
cache:
  npm: true
  directories:
    - '~/.cache'
install:
  - npm ci
script:
  - npm run test:coverage
  - sonar-scanner
  - npm run build
deploy:
  provider: surge
  project: './build/'
  domain: https://alexandersarson-starter.surge.sh
  skip_cleanup: true
